[package]
name = "rusty-tip"
version = "0.1.0"
edition = "2021"

[lib]
name = "rusty_tip"
path = "src/lib.rs"

[dependencies]
byteorder = "1.5"
thiserror = "1.0"
rand = "0.8"
log = "0.4"
env_logger = "0.10"
textplots = "0.8"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
ctrlc = "3.4"
ringbuffer = "0.16.0"
chrono = "0.4.41"
plotters = "0.3"
